source:
    gree-app1:
        category: app1
        type: gree
        pit-id: gree
        group-id: 1234

    mixi-app1:
        category: app1
        type: mixi
        pit-id: mixi
        community-id: 999

    gree-app2:
        category: app1
        type: gree
        pit-id: gree
        group-id: 9999

notifier:
    app1-jabber:
        category: app1
        type: jabber
        pit-id: jabber-app1
        chatroom: app1@conference.example.com

sleep_sec: 300 # スレッドの更新をチェックする間隔[秒]

jabber:
    # チャットルームにログインするときのニックネーム
    nick: community-comment
    # 更新の通知先チャットルーム
    room: bot@conference.example.com
    # Jabberアカウント情報を指すpit識別子
    pit-id: my-jabber-bot

gree:
    # GREEアカウント情報を指すpit識別子
    pit-id: gree
